api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Apartment', '%kernel.project_dir%/src/Domain/Hotel', '%kernel.project_dir%/src/Domain/HotelRoom']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
