doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Apartment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Apartment'
                prefix: 'App\Domain\Apartment'
                alias: Apartment
            Hotel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Hotel'
                prefix: 'App\Domain\Hotel'
                alias: Hotel
            HotelRoom:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/HotelRoom'
                prefix: 'App\Domain\HotelRoom'
                alias: HotelRoom