# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Infrastructure\Controller\:
    resource: '../src/Infrastructure/Controller'

  Infrastructure\Persistence\:
    resource: '../src/Infrastructure/Persistence'
    public: true


  infrastructure.apartment.doctrine_apartment_booking_history:
    class: Infrastructure\Persistence\Doctrine\Apartment\ApartmentBookingHistory\DoctrineApartmentBookingHistory

  infrastructure.apartment.doctrine_apartment:
    class: Infrastructure\Persistence\Doctrine\Apartment\DoctrineApartmentRepository

  Domain\Apartment\ApartmentBookingHistory\ApartmentBookingHistoryRepository: '@infrastructure.apartment.doctrine_apartment_booking_history'

  Domain\Apartment\ApartmentRepository: '@infrastructure.apartment.doctrine_apartment'

  Application\Apartment\:
    resource: '../src/Application/Apartment/*'

 # Application\Apartment\ApartmentBookingHistory\ApartmentBookingHistoryEventSubscriber:
  #  class:
# tutaj jest zdefiniowany event subscriber
 # apartment.booking_history_event_subscriber:
  #  class: Application\Apartment\ApartmentBookingHistory\ApartmentBookingHistoryEventSubscriber


  Domain\Hotel\HotelRoom\:
    resource: '../src/Domain/Hotel/HotelRoom'
  Query\Apartment\:
    resource: '../src/Query/Apartment'
  DataFixtures\:
    resource: '../tests/DataFixtures'
    tags: ['doctrine.fixture.orm']

  #    App\:
  #        resource: '../src/'
  #        exclude:
  #            - '../src/DependencyInjection/'
  #            - '../src/Entity/'
  #            - '../src/Kernel.php'
  #            - '../src/Tests/'
  #   Infrastructure\:
  #      resource: '../src/Infrastructure/'
  #   domain:
  #      namespace: Domain\
  #     resource: '../src/Domain'
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

